FROM python:3.11 AS builder

RUN mkdir /app
COPY requirements.txt /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

FROM builder AS final

COPY . /app
ENTRYPOINT [ "python", "backend/run.py"]
